### PR TITLE
Support button tag for spin

### PR DESCRIPTION
**Pull request by vsn4ik**
- [x] Fix link in `README.md`
- [x] Update Bootstrap version on `example.html`.
- [x] Update jQuery version on `example.html`.
- [x] Update Font Awesome on `example.html`. Drop v3 support. Update `*.less`.
- [x] Use Bootstrap `.text-center` instead hardcode in `*.less`.
- [x] Update jquery min version in `spinner.jquery.json`by (http://api.jquery.com/on/).
- [x] Improve JS code.
- [x] Add support Glyphicon.
- [ ] Update `.input-group-*` for Font Awesome and Glyphicon.
- [x] Add new example to `example.html`.

And add `button` tag support for spin (see ~~first~~ latest example on `example.html`).

PR ~~not~~ finished. Thanks for plugin!

### CODE REVIEW

**Comment by vsn4ik** [comment]
Finished!

**Comment by xixilive** [comment]
@vsn4ik would you like to maintain this Repo? I'll transfer it to your Github ID, deal?

**Comment by vsn4ik** [comment]
Deal. Thank you!

**Comment by xixilive** [comment]
It can not be transferred, please destroy your fork of this repo( Since it exists in your space ). and I'll try again later.

**Comment by vsn4ik** [comment]
Done.

**Pull request merged**
