### PR TITLE
Add Bower support

### PR DESCRIPTION
**Pull request by humancopy**

### CODE REVIEW

**Comment by humancopy** [comment]
Fixes to issue #15

**Comment by xixilive** [comment]
:+1:  Includes css/less and javascript files in main directive is a good solution. 
fix that please! and I'll merge your PR.

**Comment by humancopy** [comment]
I don't think need to include the CSS as it's only for Bootstrap.

**Comment by xixilive** [comment]
@humancopy Yeap! but BS is a UI-Oriented project, we need it's interactive features and visual effects all together.

**Pull request merged**
